[tox]
envlist = py311,mypy,lint
skipsdist = True

[testenv:py311]
deps =
    -rrequirements-dev.txt
setenv =
    TZ = utc
commands =
    pytest ./tests {posargs}

[testenv:mypy]
basepython = python3.11
deps =
    -rrequirements-dev.txt
commands =
    mypy --check-untyped-defs --warn-unused-ignores --no-incremental \
    	--show-error-codes \
        app.py stacks tests cache_tables create_zpt

[testenv:lint]
allowlist_externals = black
commands =
    black --check app.py stacks tests cache_tables create_zpt

[pytest]
filterwarnings =
    once::DeprecationWarning
    once::PendingDeprecationWarning
addopts = --ignore=cdk.out --ignore=odincal
