[project]
name = "odin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.2.0",
    "scipy>=1.17.0",
]

[dependency-groups]
dev = [
    "awswrangler>=3.15.0",
    "boto3>=1.42.19",
    "cartopy>=0.25.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
]
[tool.ruff]
line-length = 88
target-version = "py312"
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E203"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
