version: '3.4'

services:
  odincal:
    image: odinsmr/odincal:latest
    extra_hosts:
      - "postgres:129.16.69.112" # titan.rss.chalmers.se
    volumes:
      - /odindata/odin/level0:/odindata/odin/level0:ro
      - /root/.odincal.secret:/root/.odincal.secret:ro
    environment:
      - ODINDB_PASSWD=${ODINDB_PASSWD}
    restart: unless-stopped
