version: '3.4'

services:
  postgres:
    build: odincal/db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=odinop
      - POSTGRES_DB=odin
    restart: unless-stopped

  odincal:
    build: .
    links:
      - postgres
    volumes:
      - ./data/level0:/odindata/odin/level0:ro
    restart: unless-stopped
